DROP PROCEDURE IF EXISTS hello;
delimiter //
CREATE PROCEDURE hello()
BEGIN
    IF(CURTIME() BETWEEN '06:00:00' AND '12:00:00') THEN
SELECT 'Доброе утро';
ELSEIF(CURTIME() BETWEEN '12:00:00' AND '18:00:00') THEN
SELECT 'Добрый день';
ELSEIF(CURTIME() BETWEEN '18:00:00' AND '00:00:00') THEN
SELECT 'Добрый вечер';
ELSE
SELECT 'Доброй ночи';
END IF;
END //
delimiter ;

CALL hello();